version: '3'

networks:
  frontend:
    driver: ${NETWORKS_DRIVER}
  backend:
    driver: ${NETWORKS_DRIVER}

services:
    grafana:
      build: ./grafana
      environment:
        - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD}
      ports:
        - "${GRAFANA_PORT}:3000"
      tty: true
      networks:
        - frontend
        - backend

    node-exporter:
      build: ./nodeexporter
      volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
      ports:
        - 9100:9100
      tty: true  
      networks:
        - frontend
        - backend

    prometheus:
      build: ./prometheus
      links:
        - node-exporter
      volumes:
        - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      ports:
        - "${PROMETHEUS_PORT}:9090"
      tty: true
      networks:
        - frontend
        - backend
