version: '3'

networks:
  frontend:
    driver: ${NETWORKS_DRIVER}
  backend:
    driver: ${NETWORKS_DRIVER}

services:
    grafana:
      build: ./grafana
      environment:
        - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD}
      ports:
        - "${GRAFANA_PORT}:3000"
      tty: true
      networks:
        - frontend
        - backend

    prometheus:
      build: ./prometheus
      volumes:
        - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      ports:
        - "${PROMETHEUS_PORT}:9090"
      tty: true
      networks:
        - frontend
        - backend
