version: '3'

networks:
  frontend:
    driver: ${NETWORKS_DRIVER}
  backend:
    driver: ${NETWORKS_DRIVER}

services:
    grafana:
      build: ./grafana
      environment:
        - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD}
      ports:
        - "${GRAFANA_PORT}:3000"
      tty: true
      networks:
        - frontend
        - backend
    node-exporter:
      build: ./node-exporter
      volumes:
        - /proc:/host/proc:ro
        - /sys:/host/sys:ro
        - /:/rootfs:ro
      command: 
      - '--path.procfs=/host/proc' 
      - '--path.sysfs=/host/sys'
      - --collector.filesystem.ignored-mount-points
      - "^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)"
      ports:
        - "${NODE_EXPORTER_PORT}:9100"
      restart: always
      networks:
        - frontend
        - backend
    
    mysql-exporter:
      build: ./mysql-exporter
      volumes:
        - ./mysql-exporter/.my.cnf:/.my.cnf
      command:
        - '--config.my-cnf=.my.cnf'
      ports:
        - "${MYSQL_EXPORTER_PORT}:9104"
      networks:
        - frontend
      tty: true
      
    prometheus:
      build: ./prometheus
      volumes:
        - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      command:
        - '--config.file=/etc/prometheus/prometheus.yml'
        - '--storage.tsdb.path=/prometheus'
        - '--web.console.libraries=/usr/share/prometheus/console_libraries'
        - '--web.console.templates=/usr/share/prometheus/consoles'
      ports:
        - "${PROMETHEUS_PORT}:9090"
      tty: true
      network_mode: "host"
